on:
  push:
  
  pull_request:
  
  schedule:
    ## Run every 12 hours
    - cron:  '0 */12 * * *'
    
name: "Python CLI check"

permissions:
  contents: read

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ${{ matrix.config.os }}

    name: Python ${{ matrix.config.python }} on ${{ matrix.config.os }} [${{ matrix.config.language }}]

    strategy:
      fail-fast: false

      matrix:
        config:
          - {os: macOS-latest,   python: '3.11' }
          - {os: ubuntu-latest,  python: '3.12' }
          - {os: ubuntu-latest,  python: '3.11' }
          - {os: ubuntu-latest,  python: '3.10' }
          - {os: ubuntu-latest,  python: '3.9'  }
          - {os: ubuntu-latest,  python: '3.8'  }
          - {os: ubuntu-20.04,   python: '3.6'  }
          - {os: ubuntu-latest,  python: '3.11', language: 'C'          }
          - {os: ubuntu-latest,  python: '3.11', language: 'en_US.utf8' }
          - {os: ubuntu-latest,  python: '3.11', language: 'et_EE.utf8' }

    env:
      LANGUAGE: ${{ matrix.config.language }}
      LC_COLLATE: ${{ matrix.config.language }}
      
    steps:
    - name: Assert LANGUAGE availabilities
      if: runner.os == 'Linux'
      run: |
        sudo locale-gen et_EE.utf8
        locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
        
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.config.python }}"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install the 'seguid' Python package
      run: |
        pip install git+https://github.com/seguid/seguid-python.git
        pip install pydivsufsort

    - name: Session information
      run: |
        bash --version
        python --version
        python -m pip list
        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
        echo "LC_COLLATE: ${LC_COLLATE:-<not set>}"

    - name: Check CLI
      if: runner.os != 'Windows'
      run: make check-cli/seguid-python
